<h2 class="mb-4"><?php echo $this->tag->getTitle(); ?></h2>

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($users->count() > 0) { ?>
                <?php foreach ($users as $user) { /** @var \App\Models\User $user */ ?>
                    <tr>
                        <td><span class="font-weight-bold"><?php echo $user->getId(); ?></span></td>
                        <td><?php echo $user->getName(); ?></td>
                        <td><?php echo $user->getEmail(); ?></td>
                        <td><span class="btn font-italic" data-toggle="tooltip" data-placement="top" title="<?php echo $user->getRole()->getDescription()   ; ?>"><?php echo $user->getRoleName(); ?></span></td>
                        <td><?php echo $user->getCreatedAtFormatted(); ?></td>
                        <td><?php echo $user->getUpdatedAtFormatted(); ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr class="text-center text-muted display-4">
                    <td colspan="6">No users ...</td>
                </tr>
            <?php } ?>
        </tbody>

        <tfoot>
            <tr class="text-muted font-italic">
                <td colspan="6">Users total: <?php echo $users->count(); ?></td>
            </tr>
        </tfoot>
    </table>
</div>
