<h2><?php echo $this->tag->getTitle(); ?></h2>

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Hello, <?php echo $user->getName(); ?></h5>
        <p class="card-text"><strong>Email:</strong> <?php echo $user->getEmail(); ?></p>
        <p class="card-text"><strong>Role:</strong> <?php echo $user->getRole()->getName(); ?></p>
        <p class="card-text"><strong>Role Description:</strong> <?php echo $user->getRole()->getDescription(); ?></p>
    </div>
    <div class="card-footer">
        <p class="card-text"><small class="text-muted font-italic"><strong>CreatedAt: </strong> <?php echo $user->getCreatedAtFormatted(); ?></small></p>
    </div>
</div>
