<?php use App\Constants\RouteConst; ?>

<h2 class="mb-4"><?php echo $this->tag->getTitle(); ?></h2>

<?php echo $this->view->getPartial('partials/alerts'); ?>

<form action="<?php echo $this->url->get(['for' => RouteConst::ROUTE_NAME_REGISTER_SUBMIT]); ?>" method="POST">
    <div class="form-group">
        <label for="name">Full Name</label>
        <?php echo $form->render('name'); ?>
    </div>

    <div class="form-group">
        <label for="email">Email <span class="text-danger">*</span></label>
        <?php echo $form->render('email'); ?>
    </div>

    <div class="form-group">
        <label for="password">Password <span class="text-danger">*</span></label>
        <?php echo $form->render('password'); ?>
    </div>

    <div class="form-group">
        <label for="password_confirm">Confirm Password <span class="text-danger">*</span></label>
        <?php echo $form->render('password_confirm'); ?>
    </div>

    <div class="form-group">
        <?php echo $form->render('submit'); ?>
    </div>

</form>
