<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Phalcon4 App</h1>
        <p class="lead">This is a simple PHP Phalcon Demo Application.</p>
        <hr class="my-4">
        <p>In the GIT, a small instruction for deploying the project locally.</p>
        <p>Using automated project deployment tools - docker, scripts, etc.</p>
        <a class="btn btn-primary btn-lg"
           href="https://github.com/maksimgru/phalcon4-lesson"
           role="button"
           target="_blank"
        >
            <i class="fa fa-github"></i>
            View GitHub
        </a>
    </div>
</div>
