<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
    <a class="navbar-brand" href="#">Phalcon</a>

    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <?php
                    echo $this->tag->linkTo(['', '<i class="fa fa-home" aria-hidden="true"></i> Home', 'class' => 'nav-link']);
                ?>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <?php
                if ($this->session->has('auth_user')) {
                    echo $this->tag->linkTo(['user/profile', '<i class="fa fa-user" aria-hidden="true"></i> Profile', 'class' => 'btn btn-light mr-4']);
                    echo $this->tag->linkTo(['user/logout', '<i class="fa fa-sign-out" aria-hidden="true"></i> Logout', 'class' => 'btn btn-danger']);
                } else {
                    echo $this->tag->linkTo(['user/login', '<i class="fa fa-sign-in" aria-hidden="true"></i> Login', 'class' => 'btn btn-light mr-4']);
                    echo $this->tag->linkTo(['user/register', '<i class="fa fa-user-plus" aria-hidden="true"></i> Register', 'class' => 'btn btn-outline-light']);
                }
            ?>
        </form>
    </div>
</nav>
